### PR TITLE
Rename repositories from "maidsafe_" to "safe_"

### PR DESCRIPTION
**Pull request by rossmuir**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_nfs/17)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @krishnaIndia

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by hitman401** [comment]
Review status: 0 of 16 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[README.md, line 3 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/17#-JvZy4hjFArY2jruLOAT)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/c775b8c569bb0b0b460ae3eb62c8d79b21642ec8/README.md#L3)):</sup>
The repository still should be https://github.com/safe_nfs/maidsafe_nfs, isn't it? 

---

<sup>**[README.md, line 11 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/17#-JvZxaBeOdtqMfxT1mrS)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/c775b8c569bb0b0b460ae3eb62c8d79b21642ec8/README.md#L11)):</sup>
Jobs related to the changed URL is not present in jenkins. If the job is not configured then the badges wont be displayed.  Likewise travis wont get triggered too.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/17)

**Comment by rossmuir** [comment]
<sup>**[README.md, line 3 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/17#-JvZy4hjFArY2jruLOAT)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/c775b8c569bb0b0b460ae3eb62c8d79b21642ec8/README.md#L3)):</sup>
I dont think so @viv can maybe clarify. 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/17)

**Comment by rossmuir** [comment]
<sup>**[README.md, line 11 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/17#-JvZxaBeOdtqMfxT1mrS)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/c775b8c569bb0b0b460ae3eb62c8d79b21642ec8/README.md#L11)):</sup>
Yes thanks Krishna i will update jenkins to reflect the change when it goes live. 

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/17)

**Pull request merged**
