### PR TITLE
using travis osx and scripts

### PR DESCRIPTION
**Pull request by maqi**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_nfs/13)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @krishnaIndia (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by hitman401** [comment]
<sup>**[.travis.yml, line 17 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/13#-JvSwqcJaZ7yytGIQp4v)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/e5da5ce3f0897bc80fbfbc98eae53b52f05e7e00/.travis.yml#L17)):</sup>
After success there are scripts to generate the documentation for Version bump PR. Are we removing that process?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/13)

**Comment by maqi** [comment]
<sup>**[.travis.yml, line 17 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/13#-JvSwqcJaZ7yytGIQp4v)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/e5da5ce3f0897bc80fbfbc98eae53b52f05e7e00/.travis.yml#L17)):</sup>
it's covered in the deploy_gh-pages.sh script

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/13)

**Comment by hitman401** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/13)

**Pull request merged**
