### PR TITLE
Maid -1260_Refactored for client changes

### PR DESCRIPTION
**Pull request by hitman401**
[Review on Reviewable](https://reviewable.io/reviews/maidsafe/maidsafe_nfs/9)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
r? @ustulation

(maidsafe_highfive has picked a reviewer for you, use r? to override)

**Comment by ustulation** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

<sup>**[src/helper/directory_helper.rs, line 101 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9#-JuqF-bcyE-pg4VnZFc7)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/92d1bd26685995c03a7b2d382fd7995e97bb8513/src/helper/directory_helper.rs#L101)):</sup>
wouldn't `*mutex_client` work ? then you don't need the trait from above.

---

<sup>**[src/io/reader.rs, line 30 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9#-JuqFJsNuRzDvSo_4Mof)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/92d1bd26685995c03a7b2d382fd7995e97bb8513/src/io/reader.rs#L30)):</sup>
trailing spaces

---

<sup>**[src/io/writer.rs, line 38 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9#-JuqFOOwiL5gNNr2fWh5)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/92d1bd26685995c03a7b2d382fd7995e97bb8513/src/io/writer.rs#L38)):</sup>
trailing spaces

---

<sup>**[src/utility/mod.rs, line 2 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9#-JuqFlBlV7o4afE3Wb4K)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/92d1bd26685995c03a7b2d382fd7995e97bb8513/src/utility/mod.rs#L2)):</sup>
does this need to be in separate directory, or just utility.rs will suffice ?

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9)

**Comment by hitman401** [comment]
Review status: 10 of 13 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

<sup>**[src/helper/directory_helper.rs, line 101 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9#-JuqF-bcyE-pg4VnZFc7)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/92d1bd26685995c03a7b2d382fd7995e97bb8513/src/helper/directory_helper.rs#L101)):</sup>
Done.

---

<sup>**[src/io/reader.rs, line 30 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9#-JuqFJsNuRzDvSo_4Mof)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/92d1bd26685995c03a7b2d382fd7995e97bb8513/src/io/reader.rs#L30)):</sup>
Done.

---

<sup>**[src/io/writer.rs, line 38 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9#-JuqFOOwiL5gNNr2fWh5)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/92d1bd26685995c03a7b2d382fd7995e97bb8513/src/io/writer.rs#L38)):</sup>
Done.

---

<sup>**[src/utility/mod.rs, line 2 [r1]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9#-JuqFlBlV7o4afE3Wb4K)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/92d1bd26685995c03a7b2d382fd7995e97bb8513/src/utility/mod.rs#L2)):</sup>
Ideally we can have a directory and expose these functions in lib.rs itself.

in lib.rs
use ::nfs_utils::*;

But these refactoring can be done as a part of the upcoming task.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9)

**Comment by ustulation** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[src/helper/directory_helper.rs, line 91 [r2]](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9#-JutW7VOTPI0IMgtvYNi)** ([raw file](https://github.com/maidsafe/maidsafe_nfs/blob/cd429ba91a381e7257bce57c4a318a08d9027a5a/src/helper/directory_helper.rs#L91)):</sup>
trailing spaces

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9)

**Comment by ustulation** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/maidsafe_nfs/9)

**Pull request merged**
