### PR TITLE
MAID-1306 done and tested

### PR DESCRIPTION
**Pull request by drrosa**
**ok(try!()** is necessary in the following cases

`Ok(try!(::safe_client::structured_data_operations::versioned::get_all_versions()`
`Ok(try!(::safe_client::structured_data_operations::versioned::create()`
`Ok(try!(::safe_client::structured_data_operations::unversioned::create()`
`Ok(try!(::safe_client::utility::deserialise()`

Changing **src\helper\directory_helper.rs:133**
from
`let latest_version = versions.last().unwrap();`
 to 
`let latest_version = eval_result!(versions.last());`

causes a compilation error, so I left it unchanged.

**My bitcoin address:**
1KfJGj4j8iYdywwgZGkwsVZngaSXkTX6XL

[Review on Reviewable](https://reviewable.io/reviews/maidsafe/safe_nfs/42)

### CODE REVIEW

**Comment by maidsafe-highfive** [comment]
Thanks for the pull request, and welcome! The MaidSafe team is excited to review your changes, and you should hear from @krishnaIndia (or someone else) soon.

If any changes to this PR are deemed necessary, please add them as extra commits. This ensures that the reviewer can see what has changed since they last reviewed the code. The way GitHub handles out-of-date commits, this should also make it reasonably obvious what issues have or haven't been addressed. Large or tricky changes may require several passes of review and changes.

Please see [CONTRIBUTOR.md](../blob/master/CONTRIBUTOR) for more information.

**Comment by hitman401** [comment]
@rosatamsen Thanks for the PR.

Changing src\helper\directory_helper.rs:133
from
`let latest_version = versions.last().unwrap();`
to 
`let latest_version = eval_result!(versions.last());`

I would prefer to handle the above using [ok_or](http://doc.rust-lang.org/1.0.0-beta/std/option/enum.Option.html#method.ok_or).

For eg,

`let last_version = try!(versions.last().ok_or(::errors::NfsError::VersionNotFound));`

**Comment by hitman401** [comment]
Can you please create an account in [JIRA](https://maidsafe.atlassian.net) and let us know, So that I will be able to assign this task to you.

**Comment by drrosa** [comment]
I have already created one, I just posted a comment in the [task](https://maidsafe.atlassian.net/browse/MAID-1306).

**Comment by drrosa** [comment]
ups! I hit close and comment by mistake. Okay, I'll look into the change you mentioned above. Thanks.

**Comment by drrosa** [comment]
@ustulation Thanks for the explanation, that makes sense. However, I went for `eval_option!` because I don't feel entirely confident about adding `Unexpected` and making all the necessary additions so that it behaves like in `safe_client`. Besides, I think it might be best to do that as part of [MAID-1310](https://maidsafe.atlassian.net/browse/MAID-1310) Remove unwanted errors and Unexpected should take an &str instead of String

**Comment by ustulation** [comment]
Ah no.. You should not have to touch client module for this Task.. eval_option!() is for unrecoverable error .. this is not unrecoverable. The user can work on other directories or do other stuffs even if this one is corrupt. It will be a bad user experience to abort merely because some Logical error by a developer somewhere prevents him from doing this particular operation. Giving him a chance to continue using the client engine while nudging him to file a bug report for this one via an error message is far better.

**Comment by drrosa** [comment]
Agree, but I guess the different scenarios addressed in your first explanation confused me a bit.

So in this case, would it suffice to add the variant `Unexpected(String)` to `enum NfsError`?
and then
`let latest_version = try!(versions.last().ok_or(::errors::NfsError::Unexpected("Programming Error - Please report this as a Bug.".to_string())));`
would be proper error handling?

**Comment by ustulation** [comment]
Yes pls. So something like this:

```
<1> Add Unexpected(String) to the enum of errors
<2> Code a From trait for it - should be able to convert from a sting slice (Check safe_dns crate)
<3> Update all other necessary stuffs due to this variant addition (like Debug, Into etc)
<4> use it like ::errors::NfsError::from("Programming Error - Please report this as a Bug.")
```

Check `safe_dns` crate and try and code it exactly like that if in doubt

**Comment by hitman401** [comment]
Reviewed 3 of 4 files at r1, 2 of 2 files at r2, 4 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/maidsafe/safe_nfs/42)

**Comment by hitman401** [comment]
Thanks @rosatamsen. Seems fine to me. Good to merge. Waiting for the CI to complete. @ustulation  hope you are fine to merge this?

**Comment by NickLambert** [comment]
Thanks for all the help everyone, bounty of 0.338 on the way.

**Comment by drrosa** [comment]
Thank you all.

**Pull request merged**
